### ISSUE TITLE
Mount fails when multipathing is enabled

### ISSUE THREAD

**Issue by wilcoxwr** [hpe-storage/python-hpedockerplugin#10]
When mounting a volume, the plug-in is trying to use mkfs to create a file system on “/dev/sdf”, but it fails.  I reproduced this manually also.  Mkfs succeeds manually when using the multipath device (i.e. “dm-3”), but fails when I attempt to use the individual devices (i.e. sda, sdb, etc.).  I don’t know if this is new behavior in RHEL 7.2, but it seems that we should be using the multipath device when formatting the LUN.

Multipathing would be critical to any production environment, so I see this as an important enhancement.

**Repro steps:**
- Enable multipathing on RHEL 7.2.
- Execute "docker run -it -v <volume>:<mount> --volume-driver hpe <image> bash"

**Log Output:**
                _hpeplugin          | 2016-09-16T14:58:42+0000 [twisted.python.log#info] "-" - - [16/Sep/2016:14:58:42 +0000] "POST /VolumeDriver.Capabilities HTTP/1.1" 404 233 "-" "Go-http-client/1.1"
hpeplugin          | 2016-09-16T14:59:26+0000 [twisted.python.log#info] "-" - - [16/Sep/2016:14:59:26 +0000] "POST /VolumeDriver.Path HTTP/1.1" 200 29 "-" "Go-http-client/1.1"
hpeplugin          | 2016-09-16 14:59:33.397 11 INFO os_brick.initiator.connectors.iscsi [-] Multipath discovery for iSCSI not enabled.
hpeplugin          | 2016-09-16 14:59:33.398 11 INFO os_brick.initiator.connectors.iscsi [-] Trying to connect to iSCSI portal 192.0.2.1:3260
hpeplugin          | 2016-09-16 14:59:33.430 11 INFO sh.command [-] <Command '/bin/mkdir -p /etc/h...(101 more)' call_args {'bg': False, 'timeo...(476 more)>: starting process
hpeplugin          | 2016-09-16 14:59:33.445 11 INFO sh.command [-] <Command '/sbin/blkid -p -u fi...(17 more)' call_args {'bg': False, 'timeo...(476 more)>: starting process
hpeplugin          | 2016-09-16 14:59:33.460 11 INFO sh.command [-] <Command '/sbin/mkfs -F /dev/s...(2 more)' call_args {'bg': False, 'timeo...(476 more)>: starting process
**hpeplugin          | 2016-09-16 14:59:33.475 11 ERROR hpedockerplugin.fileutil [-](u'create file system failed exception is : %s', u"nn  RAN: '/sbin/mkfs -F /dev/sdf'nn  STDOUT:nnn  STDERR:nmke2fs 1.42.13 %2817-May-2015)\n/dev/sdf is apparently in use by the system; will not make a filesystem here!\n")**
hpeplugin          | 2016-09-16T14:59:33+0000 [_GenericHTTPChannelProtocol,1,] Unhandled Error
hpeplugin          |    Traceback (most recent call last):
hpeplugin          |      File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 241, in render
hpeplugin          |        body = resrc.render(self)
hpeplugin          |      File "/usr/lib/python2.7/site-packages/klein/resource.py", line 201, in render
hpeplugin          |        d = defer.maybeDeferred(_execute)
hpeplugin          |      File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
hpeplugin          |        result = f(_args, *_kw)
hpeplugin          |      File "/usr/lib/python2.7/site-packages/klein/resource.py", line 195, in _execute
hpeplugin          |        *_kwargs)
hpeplugin          |    --- <exception caught here> ---
hpeplugin          |      File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
hpeplugin          |        result = f(_args, *_kw)
hpeplugin          |      File "/usr/lib/python2.7/site-packages/klein/app.py", line 108, in execute_endpoint
hpeplugin          |        return endpoint_f(self._instance, *args, *_kwargs)
hpeplugin          |      File "/usr/lib/python2.7/site-packages/klein/app.py", line 193, in _f
hpeplugin          |        return _call(instance, f, request, _a, *_kw)
hpeplugin          |      File "/usr/lib/python2.7/site-packages/klein/app.py", line 35, in _call
hpeplugin          |        return f(instance, _args, *_kwargs)
hpeplugin          |      File "/python-hpedockerplugin/hpedockerplugin/hpe_storage_api.py", line 445, in volumedriver_mount
hpeplugin          |        fileutil.create_filesystem(path.path)
hpeplugin          |      File "/python-hpedockerplugin/hpedockerplugin/fileutil.py", line 60, in create_filesystem
hpeplugin          |        raise exception.HPEPluginFileSystemException(reason=msg)
hpeplugin          |    hpedockerplugin.exception.HPEPluginFileSystemException: HPE Docker Volume Plugin File System error: (u'create file system failed exception is : %s', u"\n\n  RAN: '/sbin/mkfs -F /dev/sdf'\n\n  STDOUT:\n\n\n  STDERR:\nmke2fs 1.42.13 (17-May-2015)\n/dev/sdf is apparently in use by the system; will not make a filesystem here!\n")
hpeplugin          |
hpeplugin          | 2016-09-16T14:59:33+0000 [twisted.python.log#info] "-" - - [16/Sep/2016:14:59:27 +0000] "POST /VolumeDriver.Mount HTTP/1.1" 500 6529 "-" "Go-http-client/1.1"
hpeplugin          | 2016-09-16 14:59:33.790 11 INFO hpedockerplugin.hpe_storage_api [-] In volumedriver_unmount
hpeplugin          | 2016-09-16 14:59:33.792 11 ERROR hpedockerplugin.hpe_storage_api [-](u'Volume unmount path info not found %s', u'testvol')
hpeplugin          | 2016-09-16T14:59:33+0000 [_GenericHTTPChannelProtocol,1,] Unhandled Error
hpeplugin          |    Traceback (most recent call last):
hpeplugin          |      File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 241, in render
hpeplugin          |        body = resrc.render(self)
hpeplugin          |      File "/usr/lib/python2.7/site-packages/klein/resource.py", line 201, in render
hpeplugin          |        d = defer.maybeDeferred(_execute)
hpeplugin          |      File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
hpeplugin          |        result = f(_args, *_kw)
hpeplugin          |      File "/usr/lib/python2.7/site-packages/klein/resource.py", line 195, in _execute
hpeplugin          |        *_kwargs)
hpeplugin          |    --- <exception caught here> ---
hpeplugin          |      File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
hpeplugin          |        result = f(_args, *_kw)
hpeplugin          |      File "/usr/lib/python2.7/site-packages/klein/app.py", line 108, in execute_endpoint
hpeplugin          |        return endpoint_f(self._instance, *args, *_kwargs)
hpeplugin          |      File "/usr/lib/python2.7/site-packages/klein/app.py", line 193, in _f
hpeplugin          |        return _call(instance, f, request, _a, *_kw)
hpeplugin          |      File "/usr/lib/python2.7/site-packages/klein/app.py", line 35, in _call
hpeplugin          |        return f(instance, _args, *_kwargs)
hpeplugin          |      File "/python-hpedockerplugin/hpedockerplugin/hpe_storage_api.py", line 195, in volumedriver_unmount
hpeplugin          |        raise exception.HPEPluginUMountException(reason=msg)
hpeplugin          |    hpedockerplugin.exception.HPEPluginUMountException: HPE Docker Volume Plugin Unmount Failed: (u'Volume unmount path info not found %s', u'testvol')
hpeplugin          |
hpeplugin          | 2016-09-16T14:59:33+0000 [twisted.python.log#info] "-" - - [16/Sep/2016:14:59:33 +0000] "POST /VolumeDriver.Unmount HTTP/1.1" 500 5283 "-" "Go-http-client/1.1"_

**Comment by wilcoxwr** [comment]
The enhancement was implemented and validated in plugin version 0.5.4.6-5.

The following needs to be added to hpe.conf to enable multipathing:
use_multipath = True
enforce_multipath = True
