### ISSUE TITLE
Containerized Plugin can't be started using docker-compose.yml

### ISSUE THREAD

**Issue by wdurairaj** [hpe-storage/python-hpedockerplugin#294]
Containerized plugin built using ./containerize.sh  with 3.0 (plugin_v2 ) branch code throws this error

```
Error:
docker@csosbe03b10:~/code/quick-start$ docker-compose up 2>&1 | tee /tmp/plugin.txt
Recreating plugin_legacy ... done
Attaching to plugin_legacy
plugin_legacy      | Unhandled Error
plugin_legacy      | Traceback (most recent call last):
plugin_legacy      |   File "/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/application/app.py", line 636, in parseOptions
plugin_legacy      |     usage.Options.parseOptions(self, options)
plugin_legacy      |   File "/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/python/usage.py", line 262, in parseOptions
plugin_legacy      |     for (cmd, short, parser, doc) in self.subCommands:
plugin_legacy      |   File "/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/application/app.py", line 653, in subCommands
plugin_legacy      |     for plug in sorted(plugins, key=attrgetter('tapname')):
plugin_legacy      |   File "/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/plugin.py", line 213, in getPlugins
plugin_legacy      |     allDropins = getCache(package)
plugin_legacy      | --- <exception caught here> ---
plugin_legacy      |   File "/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/plugin.py", line 171, in getCache
plugin_legacy      |     provider = pluginModule.load()
plugin_legacy      |   File "/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/python/modules.py", line 392, in load
plugin_legacy      |     return self.pathEntry.pythonPath.moduleLoader(self.name)
plugin_legacy      |   File "/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/python/reflect.py", line 308, in namedAny
plugin_legacy      |     topLevelPackage = _importAndCheckStack(trialname)
plugin_legacy      |   File "/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/python/reflect.py", line 255, in _importAndCheckStack
plugin_legacy      |     reraise(excValue, excTraceback)
plugin_legacy      |   File "/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/python/compat.py", line 463, in reraise
plugin_legacy      |     raise exception.with_traceback(traceback)
plugin_legacy      |   File "/python-hpedockerplugin/twisted/plugins/hpedockerplugin_plugin.py", line 8, in <module>
plugin_legacy      |     from hpedockerplugin.hpe_plugin_service import HpeFactory
plugin_legacy      |   File "/python-hpedockerplugin/hpedockerplugin/hpe_plugin_service.py", line 21, in <module>
plugin_legacy      |     from hpe_storage_api import VolumePlugin
plugin_legacy      | builtins.ModuleNotFoundError: No module named 'hpe_storage_api'
plugin_legacy      |
plugin_legacy      | Unhandled Error
plugin_legacy      | Traceback (most recent call last):
plugin_legacy      |   File "/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/python/usage.py", line 447, in __str__
plugin_legacy      |     return self.getSynopsis() + '\n' + self.getUsage(width=None)
plugin_legacy      |   File "/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/python/usage.py", line 484, in getUsage
plugin_legacy      |     for (cmd, short, parser, desc) in self.subCommands:
plugin_legacy      |   File "/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/application/app.py", line 653, in subCommands
plugin_legacy      |     for plug in sorted(plugins, key=attrgetter('tapname')):
plugin_legacy      |   File "/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/plugin.py", line 213, in getPlugins
plugin_legacy      |     allDropins = getCache(package)
plugin_legacy      | --- <exception caught here> ---
plugin_legacy      |   File "/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/plugin.py", line 171, in getCache
plugin_legacy      |     provider = pluginModule.load()
plugin_legacy      |   File "/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/python/modules.py", line 392, in load
plugin_legacy      |     return self.pathEntry.pythonPath.moduleLoader(self.name)
plugin_legacy      |   File "/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/python/reflect.py", line 308, in namedAny
plugin_legacy      |     topLevelPackage = _importAndCheckStack(trialname)
plugin_legacy      |   File "/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/python/reflect.py", line 255, in _importAndCheckStack
plugin_legacy      |     reraise(excValue, excTraceback)
plugin_legacy      |   File "/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/python/compat.py", line 463, in reraise
plugin_legacy      |     raise exception.with_traceback(traceback)
plugin_legacy      |   File "/python-hpedockerplugin/twisted/plugins/hpedockerplugin_plugin.py", line 8, in <module>
plugin_legacy      |     from hpedockerplugin.hpe_plugin_service import HpeFactory
plugin_legacy      |   File "/python-hpedockerplugin/hpedockerplugin/hpe_plugin_service.py", line 21, in <module>
plugin_legacy      |     from hpe_storage_api import VolumePlugin
plugin_legacy      | builtins.ModuleNotFoundError: No module named 'hpe_storage_api'
plugin_legacy      |
plugin_legacy      | Usage: twistd [options]
plugin_legacy      | Options:
plugin_legacy      |   -b, --debug          Run the application in the Python Debugger (implies
plugin_legacy      |                        nodaemon),         sending SIGUSR2 will drop into
plugin_legacy      |                        debugger
plugin_legacy      |       --chroot=        Chroot to a supplied directory before running
plugin_legacy      |   -d, --rundir=        Change to a supplied directory before running [default:
plugin_legacy      |                        .]
plugin_legacy      |   -e, --encrypted      The specified tap/aos file is encrypted.
plugin_legacy      |       --euid           Set only effective user-id rather than real user-id.
plugin_legacy      |                        (This option has no effect unless the server is running
plugin_legacy      |                        as root, in which case it means not to shed all
plugin_legacy      |                        privileges after binding ports, retaining the option to
plugin_legacy      |                        regain privileges in cases such as spawning processes.
plugin_legacy      |                        Use with caution.)
plugin_legacy      |   -f, --file=          read the given .tap file [default: twistd.tap]
plugin_legacy      |   -g, --gid=           The gid to run as.  If not specified, the default gid
plugin_legacy      |                        associated with the specified --uid is used.
plugin_legacy      |       --help           Display this help and exit.
plugin_legacy      |       --help-reactors  Display a list of possibly available reactor names.
plugin_legacy      |   -l, --logfile=       log to a specified file, - for stdout
plugin_legacy      |       --logger=        A fully-qualified name to a log observer factory to use
plugin_legacy      |                        for the initial log observer.  Takes precedence over
plugin_legacy      |                        --logfile and --syslog (when available).
plugin_legacy      |   -n, --nodaemon       don't daemonize, don't use default umask of 0077
plugin_legacy      |   -o, --no_save        do not save state on shutdown
plugin_legacy      |       --originalname   Don't try to change the process name
plugin_legacy      |   -p, --profile=       Run in profile mode, dumping results to specified file.
plugin_legacy      |       --pidfile=       Name of the pidfile [default: twistd.pid]
plugin_legacy      |       --prefix=        use the given prefix when syslogging [default: twisted]
plugin_legacy      |       --profiler=      Name of the profiler to use (profile, cprofile).
plugin_legacy      |                        [default: cprofile]
plugin_legacy      |   -r, --reactor=       Which reactor to use (see --help-reactors for a list of
plugin_legacy      |                        possibilities)
plugin_legacy      |   -s, --source=        Read an application from a .tas file (AOT format).
plugin_legacy      |       --savestats      save the Stats object rather than the text output of the
plugin_legacy      |                        profiler.
plugin_legacy      |       --spew           Print an insanely verbose log of everything that happens.
plugin_legacy      |                        Useful when debugging freezes or locks in complex code.
plugin_legacy      |       --syslog         Log to syslog, not to file
plugin_legacy      |   -u, --uid=           The uid to run as.
plugin_legacy      |       --umask=         The (octal) file creation mask to apply.
plugin_legacy      |       --version        Print version information and exit.
plugin_legacy      |   -y, --python=        read an application from within a Python file (implies
plugin_legacy      |                        -o)
plugin_legacy      |
plugin_legacy      | twistd reads a twisted.application.service.Application out of a file and runs
plugin_legacy      | it.
plugin_legacy      | Commands:
plugin_legacy      |     conch            A Conch SSH service.
plugin_legacy      |     dns              A domain name server.
plugin_legacy      |     ftp              An FTP server.
plugin_legacy      |     inetd            An inetd(8) replacement.
plugin_legacy      |     manhole          An interactive remote debugger service accessible via
plugin_legacy      |                      telnet and ssh and providing syntax coloring and basic line
plugin_legacy      |                      editing functionality.
plugin_legacy      |     portforward      A simple port-forwarder.
plugin_legacy      |     procmon          A process watchdog / supervisor
plugin_legacy      |     socks            A SOCKSv4 proxy service.
plugin_legacy      |     web              A general-purpose web server which can serve from a
plugin_legacy      |                      filesystem or application resource.
plugin_legacy      |     words            A modern words server
plugin_legacy      |     xmpp-router      An XMPP Router server
plugin_legacy      |
plugin_legacy      | /usr/bin/twistd: Unknown command: hpe_plugin_service
plugin_legacy exited with code 0
docker@csosbe03b10:~/code/quick-start$
```

**Comment by wdurairaj** [comment]
Request someone from test team to validate this fix. Since bug filing and fixing was done by me ... so i want verification by someone :-)

**Comment by wdurairaj** [comment]
Request this fix to tested by our QA team.

**Comment by prablr79** [comment]
tushar [8:04 PM]
@Prasanna M @William Durairaj Completed the sanity testing for containerized plugin built from plugin_v2 branch
as part of this testing executed automated suite and tested some scenarios manually
no issues found in this..
