### ISSUE TITLE
Bad hpe3par_api_url takes ~11 minutes to timeout.  Error message not user friendly.

### ISSUE THREAD

**Issue by ddefolo** [hpe-storage/python-hpedockerplugin#4]
If a bad entry is provided for hpe3par_api_url (perhaps good IP but wrong port) the plugin should quickly report a clear error message.

I tried an entry like the following that is otherwise correct with the exception that the port was lacking:
`hpe3par_api_url = https://172.28.6.80/api/v1`
# Issue details

That resulted in several symptoms that need to be improved:
1. Plugin initialization just sat there for 11 minutes without any clear progress
2. The error message wasn't provided as a clean "error connecting to xxx" message

See below for the output from docker logs in this case where the true root cause of there being a connection error is somewhat obscured by the way the original exception is caught handled.  Instead of having errors like this **"'ConnectionError' object has no attribute 'get_description'")**  it should just be a simple **ConnectionError** message:

full log below:
`2016-09-09 17:40:29.051 11 INFO hpedockerplugin.hpe_storage_api [-] Initialize Volume Plugin 2016-09-09 17:51:31.443 11 ERROR hpedockerplugin.hpe_storage_api [-] (u'hpeplugin_driver do_setup failed, error is: %s', u"'ConnectionError' object has no attribute 'get_description'")
2016-09-09 17:51:31.444 11 CRITICAL hpe_storage_api [-] HPEPluginNotInitializedException: HPE Docker Volume plugin not ready.
2016-09-09 17:51:31.444 11 ERROR hpe_storage_api Traceback (most recent call last):
2016-09-09 17:51:31.444 11 ERROR hpe_storage_api   File "/usr/bin/twistd", line 18, in <module>
2016-09-09 17:51:31.444 11 ERROR hpe_storage_api     run()
2016-09-09 17:51:31.444 11 ERROR hpe_storage_api   File "/usr/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 29, in run
2016-09-09 17:51:31.444 11 ERROR hpe_storage_api     app.run(runApp, ServerOptions)
2016-09-09 17:51:31.444 11 ERROR hpe_storage_api   File "/usr/lib/python2.7/site-packages/twisted/application/app.py", line 643, in run
2016-09-09 17:51:31.444 11 ERROR hpe_storage_api     runApp(config)
2016-09-09 17:51:31.444 11 ERROR hpe_storage_api   File "/usr/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
2016-09-09 17:51:31.444 11 ERROR hpe_storage_api     _SomeApplicationRunner(config).run()
2016-09-09 17:51:31.444 11 ERROR hpe_storage_api   File "/usr/lib/python2.7/site-packages/twisted/application/app.py", line 374, in run
2016-09-09 17:51:31.444 11 ERROR hpe_storage_api     self.application = self.createOrGetApplication()
2016-09-09 17:51:31.444 11 ERROR hpe_storage_api   File "/usr/lib/python2.7/site-packages/twisted/application/app.py", line 434, in createOrGetApplication
2016-09-09 17:51:31.444 11 ERROR hpe_storage_api     ser = plg.makeService(self.config.subOptions)
2016-09-09 17:51:31.444 11 ERROR hpe_storage_api   File "/python-hpedockerplugin/twisted/plugins/hpedockerplugin_plugin.py", line 25, in makeService
2016-09-09 17:51:31.444 11 ERROR hpe_storage_api     return HpeFactory(options["cfg"]).start_service()
2016-09-09 17:51:31.444 11 ERROR hpe_storage_api   File "/python-hpedockerplugin/hpedockerplugin/hpe_plugin_service.py", line 130, in start_service
2016-09-09 17:51:31.444 11 ERROR hpe_storage_api     hpepluginservice = hpedockerplugin.setupservice()
2016-09-09 17:51:31.444 11 ERROR hpe_storage_api   File "/python-hpedockerplugin/hpedockerplugin/hpe_plugin_service.py", line 114, in setupservice
2016-09-09 17:51:31.444 11 ERROR hpe_storage_api     VolumePlugin(self._reactor, hpedefaultconfig).app.resource()))
2016-09-09 17:51:31.444 11 ERROR hpe_storage_api   File "/python-hpedockerplugin/hpedockerplugin/hpe_storage_api.py", line 83, in __init__
2016-09-09 17:51:31.444 11 ERROR hpe_storage_api     raise exception.HPEPluginNotInitializedException(reason=msg)
2016-09-09 17:51:31.444 11 ERROR hpe_storage_api HPEPluginNotInitializedException: HPE Docker Volume plugin not ready.
2016-09-09 17:51:31.444 11 ERROR hpe_storage_api`
# Recommended solution
- Update the call rest calls to the 3par to support setting a **timeout** as a config value. The underlying requests package you are using supports it (see http://docs.python-requests.org/en/master/user/quickstart/#timeouts) as does the 3parclient (https://github.com/hpe-storage/python-3parclient/blob/master/hpe3parclient/client.py#L187); however, your plugin doesn’t take **timeout** as a config option like it does for **suppress_requests_ssl_warnings**.  
- Update the default for that configurable **timeout** value to something other to None.
-  Fix the exception handling logic so that the connection error message passes up cleanly.  This my need to involve making changes to the python-3parclient and/or specifically matching that exception message and then treating it differently.

**Comment by sumitshatwara** [comment]
There were 2 observations in this issue:
1)	If a bad entry is provided for hpe3par_api_url (perhaps good IP but wrong port), plugin initialization just sat there for 11 minutes without any clear progress. 
`This performance issue was not observed in our latest managed plugin 2.0.`

2)	The error message wasn't provided as a clean "error connecting to xxx" message. 
`This was observed in our latest managed plugin 2.0. Please find the logs in the attachments.`

**Comment by sumitshatwara** [comment]
This issue was still observed in legacy docker volume plugin: hpestorage/legacyvolumeplugin:2.1
