### ISSUE TITLE
Ansible Plugin installer : ssh_hosts_key_file default value is set to ~/.ssh/known_hosts 

### ISSUE THREAD

**Issue by shaik-gousa-khaja-asif** [hpe-storage/python-hpedockerplugin#532]
Steps to reproduce : 
1. Clone the python-hpedockerplugin repo
2. Leave the optional parameter ssh_hosts_key_file unspecified in properties/plugin_configuration_properties.yml
3. Run the install_hpe_3par_volume_driver.yml 

Expected Result:
After successful completion of the playbook , docker plugin must get enabled and the backends must be initialized successfully

 Actual Result:

After successful completion of the playbook , the docker plugin is running whereas the backends are not initialized due to the below error

The ssh_hosts_key_file in the hpe.conf is set to ~/.ssh/known_hosts instead of /root/.ssh/known_hosts

```
ERROR hpe3parclient.ssh [-] Error connecting via ssh: [Errno 2] No such file or directory: '~/.ssh/known_hosts': FileNotFoundError: [Errno 2] No such file or directory: '~/.ssh/known_hosts'^[[00m
2019-03-26 12:54:04.255 21 ERROR hpedockerplugin.volume_manager [-] ('hpeplugin_driver do_setup failed, error is: %s', "Error connecting via ssh: [Errno 2] No such file or directory: '~/.ssh/known_hosts'"): paramiko.ssh_exception.SSHException: Error connecting via ssh: [Errno 2] No such file or directory: '~/.ssh/known_hosts'^[[00m
2019-03-26 12:54:04.256 21 INFO hpedockerplugin.volume_manager [-] Failed to initialize 3PAR driver for array: https://192.168.67.2:8080/api/v1!Exception: HPE Docker Volume plugin not ready: ('hpeplugin_driver do_setup failed, error is: %s', "Error connecting via ssh: [Errno 2] No such file or directory: '~/.ssh/known_hosts'")^[[00m
2019-03-26 12:54:04.256 21 ERROR hpedockerplugin.backend_orchestrator [-] INITIALIZING backend: DEFAULT FAILED Error: HPE Docker Volume Plugin Start Plugin Service Failed: Failed to initialize 3PAR driver for array: https://192.168.67.2:8080/api/v1!Exception: HPE Docker Volume plugin not ready: ('hpeplugin_driver do_setup failed, error is: %s', "Error connecting via ssh: [Errno 2] No such file or directory: '~/.ssh/known_hosts'"): hpedockerplugin.exception.HPEPluginStartPluginException: HPE Docker Volume Plugin Start Plugin Service Failed: Failed to initialize 3PAR driver for array: https://192.168.67.2:8080/api/v1!Exception: HPE Docker Volume plugin not ready: ('hpeplugin_driver do_setup failed, error is: %s', "Error connecting via ssh: [Errno 2] No such file or directory: '~/.ssh/known_hosts'")^[[00m
2019-03-26 12:54:04.257 21 ERROR hpedockerplugin.backend_orchestrator [-] ERROR: None of the backends could be initialized successfully. Please rectify the configuration entries in hpe.conf and retry enable.^[[00m
2019-03-26 12:54:04.258 21 CRITICAL hpe_storage_api [-] Unhandled error: hpedockerplugin.exception.HPEPluginNotInitializedException: HPE Docker Volume plugin not ready: ERROR: None of the backends could be initialized successfully. Please rectify the configuration entries in hpe.conf and retry enable.
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api Traceback (most recent call last):
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api   File "/usr/bin/twistd", line 11, in <module>
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api     load_entry_point('Twisted==18.7.0rc1', 'console_scripts', 'twistd')()
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api   File "/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/scripts/twistd.py", line 31, in run
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api     app.run(runApp, ServerOptions)
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api   File "/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/application/app.py", line 674, in run
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api     runApp(config)
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api   File "/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/scripts/twistd.py", line 25, in runApp
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api     runner.run()
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api   File "/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/application/app.py", line 381, in run
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api     self.application = self.createOrGetApplication()
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api   File "/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/application/app.py", line 448, in createOrGetApplication
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api     ser = plg.makeService(self.config.subOptions)
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api   File "/python-hpedockerplugin/twisted/plugins/hpedockerplugin_plugin.py", line 28, in makeService
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api     return HpeFactory(options["cfg"]).start_service()
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api   File "/python-hpedockerplugin/hpedockerplugin/hpe_plugin_service.py", line 156, in start_service
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api     hpepluginservice = hpedockerplugin.setupservice()
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api   File "/python-hpedockerplugin/hpedockerplugin/hpe_plugin_service.py", line 141, in setupservice
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api     backend_configs).app.resource()))
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api   File "/python-hpedockerplugin/hpedockerplugin/hpe_storage_api.py", line 61, in __init__
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api     backend_configs)
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api   File "/python-hpedockerplugin/hpedockerplugin/backend_orchestrator.py", line 46, in __init__
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api     backend_configs)
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api   File "/python-hpedockerplugin/hpedockerplugin/backend_orchestrator.py", line 83, in initialize_manager_objects
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api     raise exception.HPEPluginNotInitializedException(reason=msg)
2019-03-26 12:54:04.258 21 ERROR hpe_storage_api hpedockerplugin.exception.HPEPluginNotInitializedException: HPE Docker Volume plugin not ready: ERROR: None of the backends could be initialized successfully. Please rectify the configuration entries in hpe.conf and retry enable.
```

**Comment by shaik-gousa-khaja-asif** [comment]
Also in the README.md file , the ssh_hosts_key_file default value should be /root/.ssh/known_hosts instead of ~/.ssh/id_rsa.pub

**Comment by farhan7500** [comment]
Thanks Asif. I'll take a look at this.

**Comment by farhan7500** [comment]
Fixed in https://github.com/hpe-storage/python-hpedockerplugin/pull/533

**Comment by shaik-gousa-khaja-asif** [comment]
Tested on latest code . Working fine
