### ISSUE TITLE
Deco word in logs and other places need changes since its not documentable word as per 3PAR docs

### ISSUE THREAD

**Issue by c-raghav** [hpe-storage/python-hpedockerplugin#705]
Deco word in logs and other places need changes since its not documentable word as per 3PAR docs

Its been seen in logs and all - place change this Deco 

2019-08-02 06:41:41,302 [ERROR] hpedockerplugin.volume_manager [140022321822600]
 MainThread ('Create volume failed with error: %s', "Invalid input received: For Deco volumes both 'dedup' and 'compression' must be specified")

refer and pick suitable from below text - to make changes accordingly

 a thin provisioned volume with compression and dedup technologies

**Comment by bhagyashree-sarawate** [comment]
Fixed and merged

**Comment by c-raghav** [comment]
Verified the 3Pardcvlog - and passing it , and closing  the defect 

1.
2019-10-14 07:21:26,470 [DEBUG] hpe3parclient.http [139998842641288] MainThread RESP BODY:

2019-10-14 07:21:26,471 [ERROR] hpedockerplugin.volume_manager [139998842641288] MainThread ('Create volume failed with error: %s', "Invalid input received: For deduplicated and compressed volume, provisioning must be specified as 'dedup' and 'compression' must be specified as true")
2019-10-14 07:21:26.471 21 ERROR hpedockerplugin.volume_manager Traceback (most recent call last):
2019-10-14 07:21:26.471 21 ERROR hpedockerplugin.volume_manager   File "/python-hpedockerplugin/hpedockerplugin/hpe/hpe_3par_common.py", line 865, in create_volume
2019-10-14 07:21:26.471 21 ERROR hpedockerplugin.volume_manager     self.client.createVolume(volume_name, cpg, capacity, extras)
2019-10-14 07:21:26.471 21 ERROR hpedockerplugin.volume_manager   File "/usr/lib/python3.6/site-packages/python_3parclient-4.2.10-py3.6.egg/hpe3parclient/client.py", line 553, in createVolume

2.

2019-10-14 07:24:35,885 [DEBUG] hpe3parclient.http [139998842641288] MainThread RESP BODY:

2019-10-14 07:24:35,885 [ERROR] hpedockerplugin.volume_manager [139998842641288] MainThread ('Create volume failed with error: %s', 'Invalid input received: To create compression enabled volume, size of the volume should be at least 16GB. Fully provisioned volume cannot be compressed. Please re-enter requested volume size or provisioning type. ')
2019-10-14 07:24:35.885 21 ERROR hpedockerplugin.volume_manager Traceback (most recent call last):
2019-10-14 07:24:35.885 21 ERROR hpedockerplugin.volume_manager   File "/python-hpedockerplugin/hpedockerplugin/volume_manager.py", line 241, in create_volume
2019-10-14 07:24:35.885 21 ERROR hpedockerplugin.volume_manager     bkend_vol_name = self._create_volume(vol, undo_steps)
2019-10-14 07:24:35.885 21 ERROR hpedockerplugin.volume_manager   File "/python-hpedockerplugin/hpedockerplugin/volume_manager.py", line 1935, in _create_volume
2019-10-14 07:24:35.885 21 ERROR hpedockerplugin.volume_manager     bkend_vol_name = self._hpeplugin_driver.create_volume(vol_specs)
2019-10-14 07:24:35.885

3.
2019-10-14 07:27:31,934 [DEBUG] etcd.client [139998842641288] MainThread Issuing read for key /volumes/ with args {'recursive': True}
2019-10-14 07:27:31,936 [INFO] hpedockerplugin.etcdutil [139998842641288] MainThread Get volbyname: volname is Test_RC
2019-10-14 07:27:31,937 [ERROR] hpe_storage_api [139998842641288] MainThread create volume failed, error is: passed compression parameter does not have a valid value. Valid values are: ['true', 'false']
